[book]
authors = ["easley"]
language = "en"
multilingual = false
src = "src"
title = "孙子兵法"

[preprocessor.theme]
pagetoc = true

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]